services:
  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: shikar-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 8000
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - shikar-network
    env_file:
      - .env

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shikar-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:8000/api}
    depends_on:
      - backend
    networks:
      - shikar-network
    env_file:
      - .env

networks:
  shikar-network:
    driver: bridge
